<a href="https://colab.research.google.com/github/jinay780/python/blob/master/Passenger_survival_rates_on_the_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd
train=pd.read_csv('titanic_train.csv')
test=pd.read_csv('titanic_test.csv')
train[:5]

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [20]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [3]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [21]:
impute_value=train['Age'].median()
train['Age']=train['Age'].fillna(impute_value)
train['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [36]:
test['Age']=test['Age'].fillna(impute_value)
test['Age']

0      34.5
1      47.0
2      62.0
3      27.0
4      22.0
       ... 
413    28.0
414    39.0
415    38.5
416    28.0
417    28.0
Name: Age, Length: 418, dtype: float64

In [41]:
test['Fare']=test['Fare'].fillna(impute_value)
test['Fare']

0        7.8292
1        7.0000
2        9.6875
3        8.6625
4       12.2875
         ...   
413      8.0500
414    108.9000
415      7.2500
416      8.0500
417     22.3583
Name: Fare, Length: 418, dtype: float64

In [42]:
test['Cabin']=test['Cabin'].fillna(impute_value)
test['Cabin']

0        28
1        28
2        28
3        28
4        28
       ... 
413      28
414    C105
415      28
416      28
417      28
Name: Cabin, Length: 418, dtype: object

In [43]:
train['IsFemale']=(train['Sex']=='female').astype(int)
test['IsFemale']=(test['Sex']=='female').astype(int)

In [44]:
predict=['Pclass','IsFemale','Age']
X_train=train[predict].values
X_test=test[predict].values
y_train=train['Survived'].values

In [45]:

X_train[:5]

array([[ 3.,  0., 22.],
       [ 1.,  1., 38.],
       [ 3.,  1., 26.],
       [ 1.,  1., 35.],
       [ 3.,  0., 35.]])

In [46]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [47]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
y_predict=model.predict(X_test)
y_predict[:10]

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0])

In [63]:
from sklearn.model_selection import cross_val_score
model=LogisticRegression()
score=cross_val_score(model,X_train,y_train,cv=4)
score

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])